version: '3'
services:
  realscraper:
    container_name: realscraper
    volumes:
      - ./:/app
    build: .
    ports:
      - "38000:38000"
      - "8000:8000"
    extra_hosts:
      - es-data-node-1.kifwat.net:10.8.0.34
      - es-data-node-2.kifwat.net:10.8.0.35
      - es-data-node-3.kifwat.net:10.8.0.41
      - node-6.kifwat.net:10.8.0.34
      - node-7.kifwat.net:10.8.0.35